# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-file-retriever:
    build:
      target: development
    image: fcp-fd-file-retriever-development
    container_name: fcp-fd-file-retriever-development
    ports:
      - "3042:3042"
      - "9042:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - fcp-fd-file-retriever

networks:
  fcp-fd-file-retriever:
    name: fcp-fd-file-retriever
    driver: bridge
