services:
  fcp-fd-file-retriever:
    build:
      context: .
      target: production
    image: fcp-fd-file-retriever
    container_name: fcp-fd-file-retriever
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-file-retriever-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
