# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-file-retriever:
    build:
      target: development
    image: fcp-fd-file-retriever-development
    container_name: fcp-fd-file-retriever-development
    ports:
      - "3042:3042"
      - "9042:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - fcp-fd-file-retriever
    depends_on:
      - fcp-fd-file-retriever-azurite
    environment:
      USE_AZURITE: ${USE_AZURITE:-true}
      AZURITE_HOST: ${AZURITE_HOST:-http://fcp-fd-file-retriever-azurite-development}
      AZURITE_BLOB_PORT: ${AZURITE_BLOB_PORT:-10000}
      AZURITE_ACCESS_KEY: ${AZURITE_ACCESS_KEY:-test}
      OBJECTS_CONTAINER_NAME: objects-${MESSAGE_DEV_SUFFIX}
      CLN_STORAGE_ACCOUNT_NAME: ${CLN_STORAGE_ACCOUNT_NAME:-cln}
      CLN_STORAGE_ACCESS_KEY: ${CLN_STORAGE_ACCESS_KEY:-test}

  fcp-fd-file-retriever-azurite:
    container_name: fcp-fd-file-retriever-azurite-development
    networks:
      - fcp-fd-file-retriever
    environment:
      AZURITE_ACCOUNTS: >
        ${CLN_STORAGE_ACCOUNT_NAME:-cln}:${AZURITE_ACCESS_KEY:-test}
    volumes:
      - azurite_data:/data

networks:
  fcp-fd-file-retriever:
    name: fcp-fd-file-retriever
    driver: bridge

volumes:
  azurite_data: