apiVersion: v2
description: File retrieval service for Single Front Door
name: fcp-fd-file-retriever
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.7.2
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
