environment: production
environmentCode:
name: fcp-fd-file-retriever
namespace: fcp-fd
workstream: fcp-fd
image: fcp-fd-file-retriever

appInsights:
  connectionString:

labels: {}

containerConfigMap:
  name: fcp-fd-file-retriever-config-map

containerSecret:
  name: fcp-fd-file-retriever-container-secret
  type: Opaque

deployment: {}

port: &port 3042

container:
  resourceTier: M
  port: *port
  clnStorageAccountName:
  clnStorageAccessKey:
  avScanPollingInterval: 5000
  avScanMaxAttempts: 10

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: fcp-fd-file-retriever
  server: