{{- include "ffc-helm-library.container-config-map" (list . "fcp-fd-file-retriever.config-map") -}}
{{- define "fcp-fd-file-retriever.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
  CLN_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.clnStorageAccountName }}
  AV_SCAN_POLLING_INTERVAL: {{ quote .Values.container.avScanPollingInterval }}
  AV_SCAN_MAX_ATTEMPTS: {{ quote .Values.container.avScanMaxAttempts }}
{{- end -}}
