{{- include "ffc-helm-library.container-config-map" (list . "fcp-fd-file-retriever.config-map") -}}
{{- define "fcp-fd-file-retriever.config-map" -}}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  PORT: {{ .Values.container.port | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Chart.Name | quote }}
{{- end -}}
