{{- include "ffc-helm-library.container-secret" (list . "fcp-fd-file-retriever.container-secret") -}}
{{- define "fcp-fd-file-retriever.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
{{- end -}}
