openapi: 3.0.0

info:
  title: Single Front Door (SFD) File Retriever
  version: 1.0.0
  description: Handles file retrieval for the fcp-fd-file-retriever microservice.

paths: 
  /objects/{id}:
    get:
      tags:
        - Object
      summary: Retrieve a file
      description: Accepts file retrieval requests via HTTP using id parameter.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of the file to be retrieved.
      responses:
        '200':
          description: File retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  path: 
                    type: string
                    format: binary
                    description: The retrieved file.
        '400':
          description: File retrieval request is invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "File download failed."
                  errors:
                    type: array
                    items:
                      type: string
                      example:
                        - Property 'path' is required.
        '404':
          description: File not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "File not found."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unexpected error occurred."

  /internal/objects/{id}:
    get:
      tags:
        - Internal
      summary: Retrieve a file (internal users)
      description: Request temporary direct access via Service SAS (Shared Access Signature) to a blob in SFD's clean storage container
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The name (UUID) of the blob to be retrieved
      responses:
        '200':
          description: SAS token successfully generated & temporary blob access granted
          content:
            application/json:
              schema:
                type: object
                properties:
                  path: 
                    type: string
                    format: url
                    description: Temporary direct access link to the retrieved blob
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unexpected error occurred."